# This file was created to clean up the raw data from the PVM(Porter Vehicle Movement) CSV files that I work with.

In [ ]:
# Upload files from local 
from google.colab import files

uploaded = files.upload() # Once cell is run, you select the file you want to clean

Saving CLD_PVM.csv to CLD_PVM (2).csv

In [ ]:
# import io and pandas then create dataframe from uploaded file (change name to new uploaded file from prior cell)
import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['CLD_PVM.csv']))
# look at how many row and columns you are working with
print(df.shape)
df.head()

(118882, 20)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (12,18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

  Stock Number Key Tag  Mod_Year  ... Total Time In Queue Comments PorterComments
0     21041562     NaN      2020  ...          30.55 mins      NaN            NaN
1          NaN  S24993      2019  ...          35.88 mins      NaN            NaN
2     21051439     NaN      2014  ...          1.19 hours      NaN            NaN
3          NaN  S28749      2020  ...          25.25 mins      NaN            NaN
4     21052166     NaN      2013  ...          35.55 mins      NaN            NaN

[5 rows x 20 columns]

## There were many "Makes" that were duplicates or were incomplete throughout the dataset, so my first clean up step was a search and replace...

In [ ]:
#This is how I looked up each make
# #Looking for substring with 'Tiffin' in it
# mask = df['Make'].str.contains('Tiffin', case=False, na=False)
# df[mask].sample(10)

In [ ]:
# I used df.loc to replace names with corrected names
# df.loc[df.Make == "Tiffin Motorhom", "Make"] = "Tiffin Motorhomes"
# df.loc[df.Make == "Tiffin", "Make"] = "Tiffin Motorhomes"
# df.loc[df.Make == "TIFFIN", "Make"] = "Tiffin Motorhomes"
# df[mask].sample(10)

In [ ]:
df.loc[df.Make == "Tiffin Motorhom", "Make"] = "Tiffin Motorhomes"
df.loc[df.Make == "Tiffin", "Make"] = "Tiffin Motorhomes"
df.loc[df.Make == "TIFFIN", "Make"] = "Tiffin Motorhomes"
df.loc[df.Make == "Thor Motor Coac", "Make"] = "Thor Motor Coach"
df.loc[df.Make == "Thor", "Make"] = "Thor Motor Coach"
df.loc[df.Make == "THOR", "Make"] = "Thor Motor Coach"
df.loc[df.Make == "Thor America", "Make"] = "Thor Motor Coach"
df.loc[df.Make == "Keystone", "Make"] = "Keystone RV"
df.loc[df.Make == "Entegra", "Make"] = "Entegra Coach"
df.loc[df.Make == "ENTEGRA", "Make"] = "Entegra Coach"
df.loc[df.Make == "Jayco/ENTEGRA", "Make"] = "Entegra Coach"
df.loc[df.Make == "NEWMAR", "Make"] = "Newmar"
df.loc[df.Make == "FLEETWOOD", "Make"] = "Fleetwood RV"
df.loc[df.Make == "Fleetwood", "Make"] = "Fleetwood RV"
df.loc[df.Make == "ITASCA", "Make"] = "Itasca"
df.loc[df.Make == "American", "Make"] = "American Coach"
df.loc[df.Make == "AMERICAN COACH", "Make"] = "American Coach"
df.loc[df.Make == "National", "Make"] = "National RV"
df.loc[df.Make == "NATIONAL", "Make"] = "National RV"
df.loc[df.Make == "WINNEBAGO", "Make"] = "Winnebago"
df.loc[df.Make == "Coachman", "Make"] = "Coachmen"
df.loc[df.Make == "MONACO", "Make"] = "Monaco"
df.loc[df.Make == "Highland Ridge", "Make"] = "Highland Ridge RV"

## Likewise, inconsistent input on the class produced too many classes

In [ ]:
df.loc[df.Class == "AG", "Class"] = "A"
df.loc[df.Class == "AD", "Class"] = "A"
df.loc[df.Class == "CLASS A", "Class"] = "A"
df.loc[df.Class == "CLASS A GAS", "Class"] = "A"
df.loc[df.Class == "CLASS A DIESEL", "Class"] = "A"
df.loc[df.Class == "A GAS", "Class"] = "A"
df.loc[df.Class == "A DIESEL", "Class"] = "A"
df.loc[df.Class == "CLASS B", "Class"] = "B"
df.loc[df.Class == "CLASS B DIESEL", "Class"] = "B"
df.loc[df.Class == "CLASS C", "Class"] = "C"
df.loc[df.Class == "CLASS C DIESEL", "Class"] = "C"
df.loc[df.Class == "5W", "Class"] = "FW"
df.loc[df.Class == "5TH WHEEL", "Class"] = "FW"
df.loc[df.Class == "PU", "Class"] = "AU"
df.loc[df.Class == "CAR", "Class"] = "AU"
df.loc[df.Class == "TRUCK", "Class"] = "AU"

## Next up, deterrming how to get to replacing class values when class not given

In [ ]:
#Looking for substring of 'Model' with 'NaN' in it
mask5 = df['Make'].str.contains('NaN', case=False, na=True)
# How many rows are affected by the NaNs in the 'Make' column
print(df[mask5].shape)
df[mask5].sample()

(173, 20)

     Stock Number Key Tag  Mod_Year  ... Total Time In Queue Comments PorterComments
2956          NaN  S26291         0  ...          49.45 mins      NaN            NaN

[1 rows x 20 columns]

In [ ]:
# #Looking for substring of 'Class' with 'NaN' in it
# mask2 = df['Class'].str.contains('NaN', case=False, na=True)
# df[mask2].sample(10)

In [ ]:
# Create DataFrame for 'No CLass'
nc_df = pd.DataFrame(df[df['Class'].str.contains('NaN', case=False, na=True)])
print(nc_df.shape)
nc_df.sample(5)

(10649, 20)

      Stock Number Key Tag  ...  Comments PorterComments
82227          NaN   14719  ...       NaN            NaN
35808          NaN  S33072  ...       NaN            NaN
46916          NaN  S33562  ...       NaN            NaN
76312          NaN   13377  ...       NaN            NaN
39094          NaN  S34529  ...       NaN            NaN

[5 rows x 20 columns]

In [ ]:
# create 'has class' DataFrame
hc_df = pd.DataFrame(df.drop(df[df['Class'].str.contains('NaN', case=False, na=True)].index))
print(hc_df.shape)
hc_df.head()

(108233, 20)

  Stock Number Key Tag  Mod_Year  ... Total Time In Queue Comments PorterComments
0     21041562     NaN      2020  ...          30.55 mins      NaN            NaN
1          NaN  S24993      2019  ...          35.88 mins      NaN            NaN
2     21051439     NaN      2014  ...          1.19 hours      NaN            NaN
3          NaN  S28749      2020  ...          25.25 mins      NaN            NaN
4     21052166     NaN      2013  ...          35.55 mins      NaN            NaN

[5 rows x 20 columns]

## The next step is to fill in the "Class" column with appropriate designations, "FW", "TT", etc.

In [ ]:
# Convert string list into list of strings, starting with the a class unit model names
a_class_string = ('Interstate, Land Yacht, See Ya, Allegiance, American Dream, American Eagle, American Tradition, Eagle, Revolution, Tradition, Dream, Contessa, Monterey, Santiam, Wonderlodge, Aurora, Cross Country, Destiny, Encore, Encounter, Mirada, Pathfinder, Pursuit, Sports Coach, Inspire, Intrigue, Astoria, Challenger, Daybreak, Escaper, Intruder, Outlaw, Tuscany, Anthem, Aspire, Cornerstone, Emblem, Insignia, Reatta, Reatta XL, Vision, Vision XL, Axon, Bounder, Coranado, Discovery, Discovery LXE, Excursion, Expedition, Fiesta, Flair, Pace Arrow, Providence, Revolution, Southwind, Storm, Terra, Berkshire, Berkshire XL, Berkshire XLT, Charleston, FR3, Georgetown, Georgetown GT3, Georgetown GT5, Georgetown GT7, Legacy, Sunseeker, Windsong, Hurricane, Serrano, Cruise Master, Landau, Sun Voyager, Yellowstone, Admiral, Ambassador, Endeavor, Imperial, Invicta, Navigator, Neptune, Scepter, Vacationer, Ellipse, Horizon, Meridian, Solei, Suncruiser, Sunova, Sunrise, Sunstar, Alante, Aspire, Precept, Presidio, Camelot, Cayman, Diplomat, Dynasty, Executive, Knight, Monarch, Trek, Vesta, Windsor, Dolphin, Sea Breeze, Tradewinds, Tropical, All Star, Bay Star, Canyon Star, Dutch Star, Dutchstar, Essex, King Aire, Kountry Star, London Aire, Mountain Aire, New Aire, Scottsdale, Ventana, Vision, Cheetah, A.C.E., Aria, Astoria, Axis, Challenger, Freedom Traveler, Hurricane, Infinity, Mandalay, Miramar, Outlaw, Palazzo, Pinnacle, Tuscany, Vegas, Venetian, Windsport, Allegro, Allegro Bay, Allegro Breeze, Allegro Bus, Allegro FRED, Allegro Open Road, Allegro RED, Breeze, Open Road, Phaeton, Zephyr, Supreme Select, Travel Supreme, Adventurer, Brave, Chieftain, Forza, Grand Tour, Intent, Journey, Sightseer, Sunstar, Tour, VECTRA, Vectra, Via, Vista, pace arrow, Allure')
a_class = a_class_string.split(", ")
print(a_class)

['Interstate', 'Land Yacht', 'See Ya', 'Allegiance', 'American Dream', 'American Eagle', 'American Tradition', 'Eagle', 'Revolution', 'Tradition', 'Dream', 'Contessa', 'Monterey', 'Santiam', 'Wonderlodge', 'Aurora', 'Cross Country', 'Destiny', 'Encore', 'Encounter', 'Mirada', 'Pathfinder', 'Pursuit', 'Sports Coach', 'Inspire', 'Intrigue', 'Astoria', 'Challenger', 'Daybreak', 'Escaper', 'Intruder', 'Outlaw', 'Tuscany', 'Anthem', 'Aspire', 'Cornerstone', 'Emblem', 'Insignia', 'Reatta', 'Reatta XL', 'Vision', 'Vision XL', 'Axon', 'Bounder', 'Coranado', 'Discovery', 'Discovery LXE', 'Excursion', 'Expedition', 'Fiesta', 'Flair', 'Pace Arrow', 'Providence', 'Revolution', 'Southwind', 'Storm', 'Terra', 'Berkshire', 'Berkshire XL', 'Berkshire XLT', 'Charleston', 'FR3', 'Georgetown', 'Georgetown GT3', 'Georgetown GT5', 'Georgetown GT7', 'Legacy', 'Sunseeker', 'Windsong', 'Hurricane', 'Serrano', 'Cruise Master', 'Landau', 'Sun Voyager', 'Yellowstone', 'Admiral', 'Ambassador', 'Endeavor', 'Imperial', 'Invicta', 'Navigator', 'Neptune', 'Scepter', 'Vacationer', 'Ellipse', 'Horizon', 'Meridian', 'Solei', 'Suncruiser', 'Sunova', 'Sunrise', 'Sunstar', 'Alante', 'Aspire', 'Precept', 'Presidio', 'Camelot', 'Cayman', 'Diplomat', 'Dynasty', 'Executive', 'Knight', 'Monarch', 'Trek', 'Vesta', 'Windsor', 'Dolphin', 'Sea Breeze', 'Tradewinds', 'Tropical', 'All Star', 'Bay Star', 'Canyon Star', 'Dutch Star', 'Dutchstar', 'Essex', 'King Aire', 'Kountry Star', 'London Aire', 'Mountain Aire', 'New Aire', 'Scottsdale', 'Ventana', 'Vision', 'Cheetah', 'A.C.E.', 'Aria', 'Astoria', 'Axis', 'Challenger', 'Freedom Traveler', 'Hurricane', 'Infinity', 'Mandalay', 'Miramar', 'Outlaw', 'Palazzo', 'Pinnacle', 'Tuscany', 'Vegas', 'Venetian', 'Windsport', 'Allegro', 'Allegro Bay', 'Allegro Breeze', 'Allegro Bus', 'Allegro FRED', 'Allegro Open Road', 'Allegro RED', 'Breeze', 'Open Road', 'Phaeton', 'Zephyr', 'Supreme Select', 'Travel Supreme', 'Adventurer', 'Brave', 'Chieftain', 'Forza', 'Grand Tour', 'Intent', 'Journey', 'Sightseer', 'Sunstar', 'Tour', 'VECTRA', 'Vectra', 'Via', 'Vista', 'pace arrow', 'Allure']

In [ ]:
b_class_string = ('Atlas, Interstate, Galleria, Orion, Ethos, Launch, Aktiv, Sunlight, Unity, Lexor, Ultra Brougham, Vilagio, Adventurous, E-Trek, SS Ideal, Versatile, Zion, Rize, Sequence, Tellaro, Cahaba, Midas, Boldt, Era, Revel, Solis, Solis Pocket, Travato, Vita')
b_class = b_class_string.split(", ")
print(b_class)

['Atlas', 'Interstate', 'Galleria', 'Orion', 'Ethos', 'Launch', 'Aktiv', 'Sunlight', 'Unity', 'Lexor', 'Ultra Brougham', 'Vilagio', 'Adventurous', 'E-Trek', 'SS Ideal', 'Versatile', 'Zion', 'Rize', 'Sequence', 'Tellaro', 'Cahaba', 'Midas', 'Boldt', 'Era', 'Revel', 'Solis', 'Solis Pocket', 'Travato', 'Vita']

In [ ]:

c_class_string = ('Prism, Orion, Concord, Qwest, Solera, Sunseeker, Navion, View, View Profile, Freedom Elite, Xalta, Citation, Compass, Gemini, Tiburon, Aspect, BT Cruiser Platinum, Concourse XL, Freelander, Leprechaun, Prism, Prism Elite, Dorado, Dutchmen, DX3, Dynaquest, Dynaquest XL, Dynasport, Europa, Force, Isata, Isata 3, Isata 4, Isata 5, Rev, Accolade, Accolade XL, Esteem, Odyssey, Qwest, Icon, Jamboree, Jamboree Searcher, Pulse, Quantum, Tioga, Forester, Lexington, Solera, Sunseeker, Chateau, Siesta, Super Nova, Atlantis, Cambria, Impulse, Navion IQ, Spirit, Embark, Escapade, Granite Ridge, Greyhawk, Melbourne, Redhawk, Seneca, Ghost, Phantom, Rebel, Triumph, Wraith, Ikon, Verona, Delano, Four Winds, Magnitude, Majestic, Omni, Synergy, Wayfarer, Access, Aspect, Chalet, Ekko, Fuse, Minnie Winnie, Outlook')
c_class = c_class_string.split(", ")
print(c_class)

['Prism', 'Orion', 'Concord', 'Qwest', 'Solera', 'Sunseeker', 'Navion', 'View', 'View Profile', 'Freedom Elite', 'Xalta', 'Citation', 'Compass', 'Gemini', 'Tiburon', 'Aspect', 'BT Cruiser Platinum', 'Concourse XL', 'Freelander', 'Leprechaun', 'Prism', 'Prism Elite', 'Dorado', 'Dutchmen', 'DX3', 'Dynaquest', 'Dynaquest XL', 'Dynasport', 'Europa', 'Force', 'Isata', 'Isata 3', 'Isata 4', 'Isata 5', 'Rev', 'Accolade', 'Accolade XL', 'Esteem', 'Odyssey', 'Qwest', 'Icon', 'Jamboree', 'Jamboree Searcher', 'Pulse', 'Quantum', 'Tioga', 'Forester', 'Lexington', 'Solera', 'Sunseeker', 'Chateau', 'Siesta', 'Super Nova', 'Atlantis', 'Cambria', 'Impulse', 'Navion IQ', 'Spirit', 'Embark', 'Escapade', 'Granite Ridge', 'Greyhawk', 'Melbourne', 'Redhawk', 'Seneca', 'Ghost', 'Phantom', 'Rebel', 'Triumph', 'Wraith', 'Ikon', 'Verona', 'Delano', 'Four Winds', 'Magnitude', 'Majestic', 'Omni', 'Synergy', 'Wayfarer', 'Access', 'Aspect', 'Chalet', 'Ekko', 'Fuse', 'Minnie Winnie', 'Outlook']

In [ ]:
auto_string = ('Alfa Romeo, BMW, Buick, Cadillac, Chevrolet, Dodge, Ford, GMC, HONDA, Hyundai, Infinity, Jaguar, Jeep, Kia, Lincoln, Mercedes, Nissan, Saturn, Subaru, Toyota, Volkswagon, Volvo, Suzuki')
autos = auto_string.split(", ")
print(autos)

['Alfa Romeo', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Dodge', 'Ford', 'GMC', 'HONDA', 'Hyundai', 'Infinity', 'Jaguar', 'Jeep', 'Kia', 'Lincoln', 'Mercedes', 'Nissan', 'Saturn', 'Subaru', 'Toyota', 'Volkswagon', 'Volvo', 'Suzuki']

In [ ]:
fw_string = ("Limited, Ambition, Cameo, Chaparral, Wyoming, Cruiser, Cruiser Aire, Rushmore, Sunset Trail, Elite Suite, Elite Suites, Fullhouse, Mobile Suite, Mobile Suites, Grand Junction, Voltage, Blue Ridge, Cardinal, Cedar Creek, Cedar Creek Champagne, Columbus, Palamino, Crusader, Riverstone, Sabre, Sandpiper, Sanibel, Shasta, Sierra, Thunder, Vengeance, Wildcat, XLR, Momentum, Reflection, Solitude, Big Country, Big Horn, Cyclone, Edge, Elkridge, Fuel, Gateway, Landmark, Milestone, Oakmont, Road Warrior, Sundance, Mesa Ridge, Open Range, Open Range Lite, Roamer, Alumascape, Next Level, Presidential Suites, North Point, Pinnacle, Seismic, Talon, Alpine, Avalanche, Carbon, Copper Canyon, Cougar High Country, Fuzion, Laredo, Montana, Montana High Country, Mountaineer, Raptor, Sprinter, Triton, Durango, Escalade, Sportster, Venom, Highlander, Spartan, Redwood, Phoenix, Solstice, Telluride, Raven, Titan, Ambition, Beacon, Pinecrest, Vilano")
fifth_wheels = fw_string.split(", ")
print(fifth_wheels)

['Limited', 'Ambition', 'Cameo', 'Chaparral', 'Wyoming', 'Cruiser', 'Cruiser Aire', 'Rushmore', 'Sunset Trail', 'Elite Suite', 'Elite Suites', 'Fullhouse', 'Mobile Suite', 'Mobile Suites', 'Grand Junction', 'Voltage', 'Blue Ridge', 'Cardinal', 'Cedar Creek', 'Cedar Creek Champagne', 'Columbus', 'Palamino', 'Crusader', 'Riverstone', 'Sabre', 'Sandpiper', 'Sanibel', 'Shasta', 'Sierra', 'Thunder', 'Vengeance', 'Wildcat', 'XLR', 'Momentum', 'Reflection', 'Solitude', 'Big Country', 'Big Horn', 'Cyclone', 'Edge', 'Elkridge', 'Fuel', 'Gateway', 'Landmark', 'Milestone', 'Oakmont', 'Road Warrior', 'Sundance', 'Mesa Ridge', 'Open Range', 'Open Range Lite', 'Roamer', 'Alumascape', 'Next Level', 'Presidential Suites', 'North Point', 'Pinnacle', 'Seismic', 'Talon', 'Alpine', 'Avalanche', 'Carbon', 'Copper Canyon', 'Cougar High Country', 'Fuzion', 'Laredo', 'Montana', 'Montana High Country', 'Mountaineer', 'Raptor', 'Sprinter', 'Triton', 'Durango', 'Escalade', 'Sportster', 'Venom', 'Highlander', 'Spartan', 'Redwood', 'Phoenix', 'Solstice', 'Telluride', 'Raven', 'Titan', 'Ambition', 'Beacon', 'Pinecrest', 'Vilano']

In [ ]:
tt_string = ("Lance, 1575, 1685, 2285, 2445, Adrenaline, Avenger, Aerolite, Aerolite Luxury, Alta, Amerilite, Ameri-Lite LE, Antigua, Apex, APEX, Apex Nano, Apex Ultra Lite, AR-1, AR-1 Extreme, AR-1 MAXX, Arrow Lite, Arctic Wolf, ARV, Ascend, Aspen Trail, Atlas, Autumn Ridge, Avenger LT, Backpack, Bambi, Base Camp, Basecamp, Brookstone, Bullet, Bullett, Bullet Premier, Bullet Premier ULTRA, Bullet Ultra Lite,  Camplite, Caravel, Catalina, Catalina Destination, Catalina Expedition, Catalina Legacy, Catalina Summit, Catalina Trail Blazer, Catalina Destination Series, Catalina Legacy Edit, Catalina Legacy Edition, Catalina Summit Seri, Catalina Summit Series, Catalina Trail Blaze, Cedar Creek, Cedar Creek Cottage, Cherokee, Cherokee ALPHA WOLF, Cherokee Alpha Wolf, Cherokee Destination, Cherokee Gray Wolf, Cherokee Grey Wolf, Cherokee Limited, Cherokee Wolf Pack, Cherokee Wolf Pup, Cherokee Wolf Pup Black Laber, Cirrus, Classic, Classic LT, Clipper, Wolf Pack, Grey Wolf, GREY WOLF,  Wolf Pup, Alpha Wolf, Clipper Cadet, Coleman, Coleman Lantern, Coleman LIGHT LX, Comet Mini, Connect, Connect SE, Conquest, Conquest GSX, 	Conquest Lite, Cougar Lite,  Flying Cloud, Nest, Cougar X-Lite, Lantern, Coyote Lite, Sunset Trail, Z-1, Zinger, Kodiak, Mallard, Prowler, Geo PRO, Hemisphere, Heritage, Heritage Glen, Hyper Lite, Lacrosse, Micro Lite, Mini Lite, NOBO, Ozark, Prime Time Avenger, R-Pod, Rockwood, Rockwood Roo, Roo, Salem, Salem Cruise Lite, Salem Grand Villa, Salem Hemisphere, Salem LE, Sandpiper, Denali, Dutchman, Dutchman Classic, E-Pro, Eagle Premier, Eagle Super Lite, EAST TO WEST SILVER LAKE, East To West Silver Lake, Edge, Elkmont, Embrace, Endurance, Escape, Excella, Featherlite, Flagstaff, FLAGSTAFF, Flagstaff E-Pro, Flagstaff Micro Lite, Flagstaff Shamrock, Flagstaff Super Lite, Flagstaff V-Lite, Flying Cloud, FLYING CLOUD, Freedom Express, Freedom Spirit, Fuel, Fun Finder, Fun Finder X, Fun Finder Xtreme Lite, FunFinder, Fury, Fuzion Series, Gazelle, Geo Pro, Globetrotter, Heartland, Hideout, HIKE, Hike, Hummingbird, Imagine, Imagine XLS, Impact, Impact Vapor Lite, International, International Sereni, International Serenity, International Signat, International Signature, Jay, Jay Feather, Jay Flight, Jay Flight SLX, Jay Flight Swift, KODIAK, Lacrosse Luxury Lite, Launch Ultra Light, Light, Lite, Mallard, Micro Lite, Micro Minnie, Minnie, Minnie Plus, Momentum G-Class, Mossy Oak, Mossy Oak Lite, MPG, Nash, No Boundaries, North Trail, Octane, One, Open Range Light, Open Range Ultra Lite, Outback, Outback., Ozark, Palomini, Palomino, Palomino Puma, Passport, Passport Elite, Passport Express, Passport Elite, Passport GT, Passport SL, Passport Ultra Lite, Pioneer, Prime Time Fury, Puma, R-Pod Hood River, Radiance, Range Lite, Residence, Rock Wood, Rockwood Mini Lite, Rockwood Sig Ultra Lite, Rockwood Signature, Rockwood Signature Lite, Rockwood Ultra Lite, Rubicon, Safari, Salem FSX, Salem fsx, Shadow Cruiser, Shadow Cruiser Ultra, Shadow Cruiser Ultra Lite, Shasta Revere, Solaire, Sonic, Sport Trek, Sport-Trek, Sportsman, Sportsmen, Sportsmen Classic, Sportsmen SE, SportTrek, Spree, Springdale, Spyder, Summerland, Surveyor, Surveyor Legend, T@B, Tab, Terry, Tommy Bahama, Torque, Tracer, Tracer AIR, Tracer Breeze, Tracer Ultra Lite, Trail Lite, Trail Runner, Transcend, Transcend Xplor, Travel Lite, Travel Star, Twilight, Ultra Lite,  Vibe, Vibe X Lite, View Finder, Viking, Viking Ultra Lite, Vintage Cruiser, Voyage, White Hawk, White Water, Wilderness,  WILDERNESS, Wildwood, Wildwood DLX, Wildwood FSX, Wildwood Grand Lodge, Wildwood LA, Wildwood LE, Wildwood Lodge, Wildwood X Lite, Wildwood X-Lite FS, Wildwood XL, Wind Jammer, Winnie Drop, Work & Play, Work and Play, XLR, XLR Boost, XLR Hyper Lite, XLR Lite, XLR Nitro, XLR Viper")
travel_trailers = tt_string.split(", ")
print(travel_trailers)

['Lance', '1575', '1685', '2285', '2445', 'Adrenaline', 'Avenger', 'Aerolite', 'Aerolite Luxury', 'Alta', 'Amerilite', 'Ameri-Lite LE', 'Antigua', 'Apex', 'APEX', 'Apex Nano', 'Apex Ultra Lite', 'AR-1', 'AR-1 Extreme', 'AR-1 MAXX', 'Arrow Lite', 'Arctic Wolf', 'ARV', 'Ascend', 'Aspen Trail', 'Atlas', 'Autumn Ridge', 'Avenger LT', 'Backpack', 'Bambi', 'Base Camp', 'Basecamp', 'Brookstone', 'Bullet', 'Bullett', 'Bullet Premier', 'Bullet Premier ULTRA', 'Bullet Ultra Lite', ' Camplite', 'Caravel', 'Catalina', 'Catalina Destination', 'Catalina Expedition', 'Catalina Legacy', 'Catalina Summit', 'Catalina Trail Blazer', 'Catalina Destination Series', 'Catalina Legacy Edit', 'Catalina Legacy Edition', 'Catalina Summit Seri', 'Catalina Summit Series', 'Catalina Trail Blaze', 'Cedar Creek', 'Cedar Creek Cottage', 'Cherokee', 'Cherokee ALPHA WOLF', 'Cherokee Alpha Wolf', 'Cherokee Destination', 'Cherokee Gray Wolf', 'Cherokee Grey Wolf', 'Cherokee Limited', 'Cherokee Wolf Pack', 'Cherokee Wolf Pup', 'Cherokee Wolf Pup Black Laber', 'Cirrus', 'Classic', 'Classic LT', 'Clipper', 'Wolf Pack', 'Grey Wolf', 'GREY WOLF', ' Wolf Pup', 'Alpha Wolf', 'Clipper Cadet', 'Coleman', 'Coleman Lantern', 'Coleman LIGHT LX', 'Comet Mini', 'Connect', 'Connect SE', 'Conquest', 'Conquest GSX', '\tConquest Lite', 'Cougar Lite', ' Flying Cloud', 'Nest', 'Cougar X-Lite', 'Lantern', 'Coyote Lite', 'Sunset Trail', 'Z-1', 'Zinger', 'Kodiak', 'Mallard', 'Prowler', 'Geo PRO', 'Hemisphere', 'Heritage', 'Heritage Glen', 'Hyper Lite', 'Lacrosse', 'Micro Lite', 'Mini Lite', 'NOBO', 'Ozark', 'Prime Time Avenger', 'R-Pod', 'Rockwood', 'Rockwood Roo', 'Roo', 'Salem', 'Salem Cruise Lite', 'Salem Grand Villa', 'Salem Hemisphere', 'Salem LE', 'Sandpiper', 'Denali', 'Dutchman', 'Dutchman Classic', 'E-Pro', 'Eagle Premier', 'Eagle Super Lite', 'EAST TO WEST SILVER LAKE', 'East To West Silver Lake', 'Edge', 'Elkmont', 'Embrace', 'Endurance', 'Escape', 'Excella', 'Featherlite', 'Flagstaff', 'FLAGSTAFF', 'Flagstaff E-Pro', 'Flagstaff Micro Lite', 'Flagstaff Shamrock', 'Flagstaff Super Lite', 'Flagstaff V-Lite', 'Flying Cloud', 'FLYING CLOUD', 'Freedom Express', 'Freedom Spirit', 'Fuel', 'Fun Finder', 'Fun Finder X', 'Fun Finder Xtreme Lite', 'FunFinder', 'Fury', 'Fuzion Series', 'Gazelle', 'Geo Pro', 'Globetrotter', 'Heartland', 'Hideout', 'HIKE', 'Hike', 'Hummingbird', 'Imagine', 'Imagine XLS', 'Impact', 'Impact Vapor Lite', 'International', 'International Sereni', 'International Serenity', 'International Signat', 'International Signature', 'Jay', 'Jay Feather', 'Jay Flight', 'Jay Flight SLX', 'Jay Flight Swift', 'KODIAK', 'Lacrosse Luxury Lite', 'Launch Ultra Light', 'Light', 'Lite', 'Mallard', 'Micro Lite', 'Micro Minnie', 'Minnie', 'Minnie Plus', 'Momentum G-Class', 'Mossy Oak', 'Mossy Oak Lite', 'MPG', 'Nash', 'No Boundaries', 'North Trail', 'Octane', 'One', 'Open Range Light', 'Open Range Ultra Lite', 'Outback', 'Outback.', 'Ozark', 'Palomini', 'Palomino', 'Palomino Puma', 'Passport', 'Passport Elite', 'Passport Express', 'Passport Elite', 'Passport GT', 'Passport SL', 'Passport Ultra Lite', 'Pioneer', 'Prime Time Fury', 'Puma', 'R-Pod Hood River', 'Radiance', 'Range Lite', 'Residence', 'Rock Wood', 'Rockwood Mini Lite', 'Rockwood Sig Ultra Lite', 'Rockwood Signature', 'Rockwood Signature Lite', 'Rockwood Ultra Lite', 'Rubicon', 'Safari', 'Salem FSX', 'Salem fsx', 'Shadow Cruiser', 'Shadow Cruiser Ultra', 'Shadow Cruiser Ultra Lite', 'Shasta Revere', 'Solaire', 'Sonic', 'Sport Trek', 'Sport-Trek', 'Sportsman', 'Sportsmen', 'Sportsmen Classic', 'Sportsmen SE', 'SportTrek', 'Spree', 'Springdale', 'Spyder', 'Summerland', 'Surveyor', 'Surveyor Legend', 'T@B', 'Tab', 'Terry', 'Tommy Bahama', 'Torque', 'Tracer', 'Tracer AIR', 'Tracer Breeze', 'Tracer Ultra Lite', 'Trail Lite', 'Trail Runner', 'Transcend', 'Transcend Xplor', 'Travel Lite', 'Travel Star', 'Twilight', 'Ultra Lite', ' Vibe', 'Vibe X Lite', 'View Finder', 'Viking', 'Viking Ultra Lite', 'Vintage Cruiser', 'Voyage', 'White Hawk', 'White Water', 'Wilderness', ' WILDERNESS', 'Wildwood', 'Wildwood DLX', 'Wildwood FSX', 'Wildwood Grand Lodge', 'Wildwood LA', 'Wildwood LE', 'Wildwood Lodge', 'Wildwood X Lite', 'Wildwood X-Lite FS', 'Wildwood XL', 'Wind Jammer', 'Winnie Drop', 'Work & Play', 'Work and Play', 'XLR', 'XLR Boost', 'XLR Hyper Lite', 'XLR Lite', 'XLR Nitro', 'XLR Viper']

In [ ]:
pt_string = ("Sport, SPORT, Somerset, Rockwood Premier High Wall, Rockwood Premier Hig, Rockwood Premier A, Rockwood Premier, Rockwood Freedom LTD, Rockwood Freedom, Rockwood ESP, Rockwood, Nigra, Mac, MAC, Jay Series Sport, Jay Series, Freedom Express, Freedom, Flag staff, Flagstaff, Flag staff, Flagstaff SE, Flagstaff M.A.C. LTD, Flagstaff M.A.C., Flagstaff Classic Hard Side, Comet, COMET, Premier, Centennial, Bayside, Avalon, Americana, A Liner, A_LINER")
pop_ups = pt_string.split(", ")
print(pop_ups)

['Sport', 'SPORT', 'Somerset', 'Rockwood Premier High Wall', 'Rockwood Premier Hig', 'Rockwood Premier A', 'Rockwood Premier', 'Rockwood Freedom LTD', 'Rockwood Freedom', 'Rockwood ESP', 'Rockwood', 'Nigra', 'Mac', 'MAC', 'Jay Series Sport', 'Jay Series', 'Freedom Express', 'Freedom', 'Flag staff', 'Flagstaff', 'Flag staff', 'Flagstaff SE', 'Flagstaff M.A.C. LTD', 'Flagstaff M.A.C.', 'Flagstaff Classic Hard Side', 'Comet', 'COMET', 'Premier', 'Centennial', 'Bayside', 'Avalon', 'Americana', 'A Liner', 'A_LINER']

In [ ]:
tc_string = ("Arctic Fox, Silver Fox, SILVER FOX, Backpack Series, Lance Longbed, Lance Shortbed, RPM")
truck_campers = tc_string.split(", ")
print(truck_campers)

['Arctic Fox', 'Silver Fox', 'SILVER FOX', 'Backpack Series', 'Lance Longbed', 'Lance Shortbed', 'RPM']

In [ ]:
from numpy.lib.arraysetops import isin

nc_df.loc[nc_df['Model'].isin(a_class), 'Class'] = 'A'
nc_df.loc[nc_df['Model'].isin(b_class), 'Class'] = 'B'
nc_df.loc[nc_df['Model'].isin(c_class), 'Class'] = 'C'
nc_df.loc[nc_df['Model'].isin(fifth_wheels), 'Class'] = 'FW'
nc_df.loc[nc_df['Model'].isin(travel_trailers), 'Class'] = 'TT'
nc_df.loc[nc_df['Model'].isin(pop_ups), 'Class'] = 'PT'
nc_df.loc[nc_df['Model'].isin(truck_campers), 'Class'] = 'TC'
nc_df.loc[nc_df['Make'].isin(autos), 'Class'] = 'AU'

In [ ]:
# Check nc_df to see if class corrected
print(nc_df.shape)
nc_df.sample(20)

(10649, 20)

       Stock Number Key Tag  ...  Comments PorterComments
16961           NaN  S34112  ...       NaN            NaN
19624           NaN  S36816  ...       NaN            NaN
27871           NaN  S34668  ...       NaN            NaN
5535            NaN  S26280  ...       NaN            NaN
8048            NaN  S30533  ...       NaN            NaN
29213           NaN  S34514  ...       NaN            NaN
116721          NaN   14282  ...       NaN            NaN
51004           NaN  S40564  ...       NaN            NaN
52242           NaN  S40809  ...       NaN            NaN
13235           NaN  S22964  ...       NaN            NaN
43926           NaN  S33892  ...       NaN            NaN
39581           NaN  S27133  ...       NaN            NaN
10574           NaN  S36847  ...       NaN            NaN
16067           NaN  S36751  ...       NaN            NaN
32282           NaN  S34962  ...       NaN            NaN
86685           NaN   12806  ...       NaN            NaN
21058           NaN  S36323  ...       NaN            NaN
22206           NaN  S35194  ...       NaN            NaN
72079           NaN   13393  ...       NaN            NaN
71003           NaN   15067  ...       NaN            NaN

[20 rows x 20 columns]

In [ ]:
mask3 = nc_df['Class'].str.contains('NaN', case=False, na=True)

print(nc_df[mask5].shape)
nc_df[mask3].sample()

(171, 20)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

      Stock Number Key Tag  ...  Comments PorterComments
83971          NaN   15498  ...       NaN            NaN

[1 rows x 20 columns]

In [ ]:
# concat
clean_df = pd.concat([nc_df, hc_df])
print(clean_df.shape)
clean_df.head()

(118882, 20)

   Stock Number Key Tag  Mod_Year  ... Total Time In Queue Comments PorterComments
20          NaN  S26167      2015  ...          24.10 mins      NaN            NaN
37          NaN  S22938      2006  ...          15.95 mins      NaN            NaN
39          NaN  S22393      2005  ...          12.68 mins      NaN            NaN
44          NaN  S22940      2018  ...           8.57 mins      NaN            NaN
71          NaN  S28744      2014  ...          55.83 mins      NaN            NaN

[5 rows x 20 columns]

In [ ]:
mask4 = clean_df['Class'].str.contains('NaN', case=False, na=True)

print(clean_df[mask5].shape)
clean_df[mask4].sample(20)

(173, 20)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

       Stock Number  ... PorterComments
83962           NaN  ...            NaN
3507            NaN  ...            NaN
11987           NaN  ...            NaN
36179           NaN  ...            NaN
102123          NaN  ...            NaN
111247          NaN  ...            NaN
73591           NaN  ...            NaN
19081           NaN  ...            NaN
27111           NaN  ...            NaN
5390            NaN  ...            NaN
7190            NaN  ...            NaN
79234           NaN  ...            NaN
32823           NaN  ...            NaN
55401           NaN  ...            NaN
109010          NaN  ...            NaN
113338          NaN  ...            NaN
114223          NaN  ...            NaN
6073            NaN  ...            NaN
31215           NaN  ...            NaN
8107            NaN  ...            NaN

[20 rows x 20 columns]

## This section crates a new column called "Type", which will be used to show the ratio of towable units vs. motorized units in future visualizations.

In [ ]:
#create type column
towable = ['FW', 'TT', 'PT', 'CT', 'TC', 'CA', 'BT']
motorized = ['A', 'B', 'C', 'AU']
type = []

for row in clean_df['Class']:
    if row in towable:
        type.append('Towable')
    elif row in motorized:
        type.append('Motorized')
    else:
        type.append('Inc Input')
        
clean_df.insert(5,'Type',type,True)

clean_df.sample(5)

       Stock Number Key Tag  ...  Comments PorterComments
51415      21070822     NaN  ...       NaN            NaN
89422           NaN  T10039  ...       NaN            NaN
117558     21113474     NaN  ...       NaN            NaN
83874           NaN   15498  ...       NaN            NaN
35792      21062437     NaN  ...       NaN            NaN

[5 rows x 21 columns]

## Final cleaning, replacing 'NaN's with 0 and removing the comma from the 'Porter ID' column, then download!

In [ ]:
# import Numpy
import numpy as np
# drop NaNs
clean_df = clean_df.replace(np.nan,0)
clean_df.sample(10)

      Stock Number Key Tag  ...  Comments PorterComments
64936     21070882       0  ...         0              0
84759     21097448       0  ...         0              0
2985             0  S26307  ...         0              0
22467            0  S36013  ...         0              0
23230            0  S36020  ...         0              0
63710     21067266       0  ...         0              0
88538     21081890       0  ...         0              0
49776     21056753       0  ...         0              0
27562            0  S36484  ...         0              0
20427     21057542       0  ...         0              0

[10 rows x 21 columns]

In [ ]:
# remove the comma from Porter ID and change to int
clean_df[["Porter ID"]] = clean_df[["Porter ID"]].replace(',','', regex=True).astype(int)
clean_df.sample(10)

       Stock Number  ... PorterComments
40428      21066582  ...              0
34006      21058949  ...              0
15589             0  ...              0
104251     21104988  ...              0
31357             0  ...              0
86795      21066201  ...              0
57841             0  ...              0
94189      21083808  ...              0
112894            0  ...              0
69512      21083746  ...              0

[10 rows x 21 columns]

In [ ]:
# #download to local (change file name)
from google.colab import files
# save df to csv, with index set to "False" to avoid an additional column
clean_df.to_csv('Clean_CLD_PVM.csv', index = False)
# name file to download
files.download('Clean_CLD_PVM.csv')